INSERT INTO LocalizedText (Language, Tag, Text) VALUES
('en_US', 'LOC_TRAIT_LEADER_AURORA_SANCTUARY_DESCRIPTION', 'Amphitheaters, Lighthouses, Shrines, Universities, Banks and Factories grants +1 corresponding yield for all unimproved Charming tiles, +2 for all unimproved Breathtaking tiles to the city they are in. Terrain yields of Tundra and Snow (including Hills) tiles are adjusted to +2 [ICON_Food] Food and +2 [ICON_Production] Production. Units heal +10 HP faster in Charming or Breathtaking tiles.{LOC_TRAIT_GOURMET_EDIFICE_BONUS}'),
('en_US', 'LOC_TRAIT_CIVILIZATION_LANDSOL_KOKKORO_PRINCESS_DESCRIPTION', 'Grants an extra leader trait {LOC_TRAIT_LEADER_AURORA_SANCTUARY_NAME} for Kokkoro (Princess): {LOC_TRAIT_LEADER_AURORA_SANCTUARY_DESCRIPTION}'),
('zh_Hans_CN', 'LOC_TRAIT_LEADER_AURORA_SANCTUARY_DESCRIPTION', '古罗马剧场、灯塔、神社、大学、银行和工厂为所在城市所有迷人的未改良单元格+1相应产出，惊艳的未改良单元格则+2。冻土和雪地（含丘陵）的地形产出调整为 +2 [ICON_Food] 食物和 +2 [ICON_Production] 生产力。单位位于迷人或惊艳单元格每回合可多恢复10点生命值。{LOC_TRAIT_GOURMET_EDIFICE_BONUS}'),
('zh_Hans_CN', 'LOC_TRAIT_CIVILIZATION_LANDSOL_KOKKORO_PRINCESS_DESCRIPTION', '为可可萝（公主）增加一个额外的领袖特性“{LOC_TRAIT_LEADER_AURORA_SANCTUARY_NAME}”: {LOC_TRAIT_LEADER_AURORA_SANCTUARY_DESCRIPTION}');
	
UPDATE LocalizedText SET Text = '+100% [ICON_Production] Production towards the Preserve district. Preserve buildings have their effect range extended by 1 and can be purchased with [ICON_Faith] Faith. Terrain yields of Tundra and Snow (including Hills) tiles are adjusted to +2 [ICON_Food] Food and +2 [ICON_Production] Production. Units heal +10 HP faster in Charming or Breathtaking tiles.{LOC_TRAIT_GOURMET_EDIFICE_BONUS}' WHERE EXISTS (SELECT * FROM LocalizedText WHERE Tag = 'LOC_CIVILIZATION_VIETNAM_NAME') AND Tag = 'LOC_TRAIT_LEADER_AURORA_SANCTUARY_DESCRIPTION' AND Language = 'en_US';
UPDATE LocalizedText SET Text = '建造保护区时 +100% [ICON_Production] 生产力。保护区建筑的效果范围增大1且可以使用 [ICON_Faith] 信仰值购买。冻土和雪地（含丘陵）的地形产出调整为 +2 [ICON_Food] 食物和 +2 [ICON_Production] 生产力。单位位于迷人或惊艳单元格每回合可多恢复10点生命值。{LOC_TRAIT_GOURMET_EDIFICE_BONUS}' WHERE EXISTS (SELECT * FROM LocalizedText WHERE Tag = 'LOC_CIVILIZATION_VIETNAM_NAME') AND Tag = 'LOC_TRAIT_LEADER_AURORA_SANCTUARY_DESCRIPTION' AND Language = 'zh_Hans_CN';

UPDATE LocalizedText SET Text = 'Grants an extra leader trait {LOC_TRAIT_LEADER_AURORA_SANCTUARY_NAME} for Kokkoro (Princess): {LOC_TRAIT_LEADER_AURORA_SANCTUARY_DESCRIPTION}' WHERE EXISTS (SELECT * FROM LocalizedText WHERE Tag = 'LOC_CIVILIZATION_VIETNAM_NAME') AND Tag = 'LOC_TRAIT_CIVILIZATION_LANDSOL_KOKKORO_PRINCESS_DESCRIPTION' AND Language = 'en_US';
UPDATE LocalizedText SET Text = '为可可萝（公主）增加一个额外的领袖特性“{LOC_TRAIT_LEADER_AURORA_SANCTUARY_NAME}”：{LOC_TRAIT_LEADER_AURORA_SANCTUARY_DESCRIPTION}' WHERE EXISTS (SELECT * FROM LocalizedText WHERE Tag = 'LOC_CIVILIZATION_VIETNAM_NAME') AND Tag = 'LOC_TRAIT_CIVILIZATION_LANDSOL_KOKKORO_PRINCESS_DESCRIPTION' AND Language = 'zh_Hans_CN';