INSERT INTO LocalizedText (Language, Tag, Text) VALUES
('en_US', 'LOC_TRAIT_LEADER_AURORA_SANCTUARY_DESCRIPTION', 'Amphitheaters, Lighthouses, Shrines, Universities, Banks and Factories grants +1 corresponding yield for all unimproved Charming tiles, +2 for all unimproved Breathtaking tiles to the city they are in. Units heal +10 HP faster and can heal after actions in Charming or Breathtaking tiles.{LOC_TRAIT_GOURMET_EDIFICE_BONUS}'),
('en_US', 'LOC_TRAIT_CIVILIZATION_LANDSOL_KOKKORO_PRINCESS_DESCRIPTION', 'Grants an extra leader trait {LOC_TRAIT_LEADER_AURORA_SANCTUARY_NAME} for Kokkoro (Princess): {LOC_TRAIT_LEADER_AURORA_SANCTUARY_DESCRIPTION}'),
('zh_Hans_CN', 'LOC_TRAIT_LEADER_AURORA_SANCTUARY_DESCRIPTION', '古罗马剧场、灯塔、神社、大学、银行和工厂为所在城市所有迷人的未改良单元格+1相应产出，惊艳的未改良单元格则+2。单位位于迷人或惊艳单元格每回合可多恢复10点生命值，且可于行动后恢复。{LOC_TRAIT_GOURMET_EDIFICE_BONUS}'),
('zh_Hans_CN', 'LOC_TRAIT_CIVILIZATION_LANDSOL_KOKKORO_PRINCESS_DESCRIPTION', '为可可萝（公主）增加一个额外的领袖特性“{LOC_TRAIT_LEADER_AURORA_SANCTUARY_NAME}”: {LOC_TRAIT_LEADER_AURORA_SANCTUARY_DESCRIPTION}'),
('ko_KR', 'LOC_TRAIT_LEADER_AURORA_SANCTUARY_DESCRIPTION', '원형극장, 등대, 성소, 대학교, 은행과 공장이 각자의 분야에 맞는 산출을 모든 미개발된 멋진 매력도 타일에 +1 제공하고, 미개발된 놀라운 매력도 타일에 +2 제공합니다. 멋지거나 놀라운 매력도 이상의 타일에 있는 유닛은 행동 후에도 회복할수 있고, 회복량이 +10 증가합니다.{LOC_TRAIT_GOURMET_EDIFICE_BONUS}'),
('ko_KR', 'LOC_TRAIT_CIVILIZATION_LANDSOL_KOKKORO_PRINCESS_DESCRIPTION', '콧코로(프린세스 폼)에게  {LOC_TRAIT_LEADER_AURORA_SANCTUARY_NAME} 특성을 부여합니다: {LOC_TRAIT_LEADER_AURORA_SANCTUARY_DESCRIPTION}');	

UPDATE LocalizedText SET Text = 'Preserve districts are granted +1 [ICON_Food] Food from adjacent Tundra tiles, [ICON_Culture] Culture and [ICON_Production] Production equal to their [ICON_Housing] Housing bonus, and 100% faster to build. Preserve buildings have their effect range extended by 1 and can be purchased with [ICON_Faith] Faith. Units heal +10 HP faster and can heal after actions in Charming or Breathtaking tiles.{LOC_TRAIT_GOURMET_EDIFICE_BONUS}' WHERE EXISTS (SELECT * FROM LocalizedText WHERE Tag = 'LOC_CIVILIZATION_VIETNAM_NAME') AND Tag = 'LOC_TRAIT_LEADER_AURORA_SANCTUARY_DESCRIPTION' AND Language = 'en_US';
UPDATE LocalizedText SET Text = '保护区从相邻冻土单元格获得+1 [ICON_Food] 食物，获得与其 [ICON_Housing] 住房加成相等的 [ICON_Culture] 文化值与 [ICON_Production] 生产力，且建造加速100%。保护区建筑的效果范围增大1且可以使用 [ICON_Faith] 信仰值购买。单位位于迷人或惊艳单元格每回合可多恢复10点生命值，且可于行动后恢复。{LOC_TRAIT_GOURMET_EDIFICE_BONUS}' WHERE EXISTS (SELECT * FROM LocalizedText WHERE Tag = 'LOC_CIVILIZATION_VIETNAM_NAME') AND Tag = 'LOC_TRAIT_LEADER_AURORA_SANCTUARY_DESCRIPTION' AND Language = 'zh_Hans_CN';
UPDATE LocalizedText SET Text = '보존이 인접 툰드라 타일에 [ICON_Food] 식량을 +1 제공하며, [ICON_Housing] 주거공간만큼 [ICON_Culture] 문화와 [ICON_Production] 생산력을 산출하고, 건설 속도가 100% 빨라집니다. 보존 건물들의 효과 범위가 1칸 늘어나며 [ICON_Faith] 신앙으로 구매 가능해집니다. 멋지거나 놀라운 매력도의 타일에서 유닛들은 행동을 마치고도 회복할수 있으며, 회복력이 +10 증가합니다.{LOC_TRAIT_GOURMET_EDIFICE_BONUS}' WHERE EXISTS (SELECT * FROM LocalizedText WHERE Tag = 'LOC_CIVILIZATION_VIETNAM_NAME') AND Tag = 'LOC_TRAIT_LEADER_AURORA_SANCTUARY_DESCRIPTION' AND Language = 'ko_KR';

UPDATE LocalizedText SET Text = 'Grants an extra leader trait {LOC_TRAIT_LEADER_AURORA_SANCTUARY_NAME} for Kokkoro (Princess): {LOC_TRAIT_LEADER_AURORA_SANCTUARY_DESCRIPTION}' WHERE EXISTS (SELECT * FROM LocalizedText WHERE Tag = 'LOC_CIVILIZATION_VIETNAM_NAME') AND Tag = 'LOC_TRAIT_CIVILIZATION_LANDSOL_KOKKORO_PRINCESS_DESCRIPTION' AND Language = 'en_US';
UPDATE LocalizedText SET Text = '为可可萝（公主）增加一个额外的领袖特性“{LOC_TRAIT_LEADER_AURORA_SANCTUARY_NAME}”：{LOC_TRAIT_LEADER_AURORA_SANCTUARY_DESCRIPTION}' WHERE EXISTS (SELECT * FROM LocalizedText WHERE Tag = 'LOC_CIVILIZATION_VIETNAM_NAME') AND Tag = 'LOC_TRAIT_CIVILIZATION_LANDSOL_KOKKORO_PRINCESS_DESCRIPTION' AND Language = 'zh_Hans_CN';
UPDATE LocalizedText SET Text = '콧코로(프린세스 폼)에게  {LOC_TRAIT_LEADER_AURORA_SANCTUARY_NAME} 특성을 부여합니다: {LOC_TRAIT_LEADER_AURORA_SANCTUARY_DESCRIPTION}' WHERE EXISTS (SELECT * FROM LocalizedText WHERE Tag = 'LOC_CIVILIZATION_VIETNAM_NAME') AND Tag = 'LOC_TRAIT_CIVILIZATION_LANDSOL_KOKKORO_PRINCESS_DESCRIPTION' AND Language = 'ko_KR';
